services:
    _defaults:
        autowire: true          # Automatically injects dependencies in your services.
        autoconfigure: true     # Automatically registers your services as commands, event subscribers, etc.
        public: true           # Allows optimizing the container by removing unused services; this also means
                                # fetching services directly from the container via $container->get() won't work.
                                # The best practice is to be explicit about your dependencies anyway.
        bind:
            #$projectDir: '%kernel.project_dir%'

    Newhorizondesign\ContaoChartjsDiagramms\:
        resource: ../../
        exclude: ../../{DependencyInjection,Resources,Model}

    Newhorizondesign\ContaoChartjsDiagramms\Controller\FrontendModule\ListenChartjsModulesController:
        public: true
        tags:
            - { name: container.service_subscriber }
            - { name: controller.service_arguments }
        # Since Symfony 5 the container has to be set manually
        calls:
            - [ setContainer, [ '@Psr\Container\ContainerInterface' ] ]
        arguments:
            - '@twig'

